version: '3.1'
services:
  api:
    container_name: nasa-apod-web-test
    restart: always
    image: nasa-apod
    ports:
      - "8080:80"
    build:
      context: ./
      args: 
        API_KEY: "<NASA_APOD_API_KEY>"